---

- name: Testing importing group and host vars via Tower
  hosts: all
  gather_facts: no
  connection: local
  vars:
    bigip_admin_credentials: admin

    - name: Create sync failover group
      bigip_device_group:
        name: "{{ ha_group }}"
        auto_sync: no
        type: sync-failover
        provider:
          user: admin
          server: "{{ ansible_host }}"
          password: "{{ bigip_admin_credentials }}"
          validate_certs: no
