---

- name: Create Internal and External VLAN
  hosts: all
  gather_facts: no
  connection: local
  vars:
    bigip_admin_credentials: admin

  tasks:
    - name: Create VLAN External
      bigip_vlan:
        name: "{{ vlan10_name }}"
        tagged_interfaces: "{{ vlan10_interface }}"
        tag: "{{ tag_id_external }}"
        provider:
          user: admin
          server: "{{ ansible_host }}"
          password: "{{ bigip_admin_credentials }}"
          validate_certs: no
    - name: Create VLAN Internal
      bigip_vlan:
        name: "{{ vlan20_name }}"
        tagged_interfaces: "{{ vlan20_interface }}"
        tag: "{{ tag_id_internal }}"
        provider:
          user: admin
          server: "{{ ansible_host }}"
          password: "{{ bigip_admin_credentials }}"
          validate_certs: no
