---

- name: Establish device trust from BIGIP1
  hosts: bigip1
  gather_facts: no
  connection: local
  vars:
    bigip_admin_credentials: admin

  tasks: 
    - name: Establish device trust
      bigip_device_trust:
        peer_server: "{{ bigip2_ip }}"
        peer_user: "{{ user }}"
        peer_password: "{{ password }}"
        provider:
          user: admin
          server: "{{ ansible_host }}"
          password: "{{ bigip_admin_credentials }}"
          validate_certs: no
