---

- name: Add ntp and dns server
  hosts: all
  gather_facts: no
  connection: local
  vars:
    bigip_admin_credentials: admin

  tasks:
    - name: Configure NTP
      bigip_device_ntp:
        ntp_servers: "{{ ntp_addr }}"
        validate_certs: no
    - name: Configure DNS1
      bigip_device_dns:
        name_servers: "{{ dns_addr1 }}"
        validate_certs: no
    - name: Configure DNS2
      bigip_device_dns:
        name_servers: "{{ dns_addr2 }}"
        validate_certs: no
