---

- name: Create Internal and External VLAN
  hosts: all
  gather_facts: no
  connection: local
  vars:
    bigip_admin_credentials: admin

  tasks:
    - name: Create Self IP on vlan10
      bigip_selfip:
        address: "{{ selfip1_1 }}"
        netmask: "{{ netmask_1 }}"
        name: "{{ selfip1_1 }}"
        vlan: "{{ vlan10_name }}"
        allow_service: default
        validate_certs: no
    - name: Create Self IP on vlan20
      bigip_selfip:
        address: "{{ selfip1_2 }}"
        netmask: "{{ netmask_1 }}"
        name: "{{ selfip1_2 }}"
        vlan: "{{ vlan20_name }}"
        allow_service: default
        validate_certs: no

